/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.realeastprojectasin;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author gelo
 */
public class ALLSTATS extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ALLSTATS.class.getName());

    /**
     * Creates new form ALLSTATS
     */
    public ALLSTATS() {
        initComponents();
        setLocationRelativeTo(null);
        loadAllStatistics();
    }
        private void loadAllStatistics() {
        loadTopStats();
        loadQuizzesCreated();
        loadQuizzesTaken();
        loadPerformanceBySubject();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setText("Overall Statistics");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("QUIZZES YOU CREATED");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("QUIZZES YOU TOOK");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("PERFORMANCE BY SUBJECTS");

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)))))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ALLSTATS().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    private void loadTopStats() {
        try {
            Connection conn = DBConnection.getConnection();
            int userId = AccountManager.getCurrentUserId();
            
            // Count quizzes created
            String query1 = "SELECT COUNT(*) as total FROM quizzes WHERE creator_id = ?";
            PreparedStatement ps1 = conn.prepareStatement(query1);
            ps1.setInt(1, userId);
            ResultSet rs1 = ps1.executeQuery();
            if (rs1.next()) {
                jLabel2.setText("Quizzes Created: " + rs1.getInt("total"));
            }
            rs1.close();
            ps1.close();
            
            // Count quizzes taken
            String query2 = "SELECT COUNT(*) as total FROM responses WHERE user_id = ?";
            PreparedStatement ps2 = conn.prepareStatement(query2);
            ps2.setInt(1, userId);
            ResultSet rs2 = ps2.executeQuery();
            if (rs2.next()) {
                jLabel3.setText("Quizzes Taken: " + rs2.getInt("total"));
            }
            rs2.close();
            ps2.close();
            
            // Calculate average score
            String query3 = "SELECT AVG(score) as avg_score FROM responses WHERE user_id = ?";
            PreparedStatement ps3 = conn.prepareStatement(query3);
            ps3.setInt(1, userId);
            ResultSet rs3 = ps3.executeQuery();
            if (rs3.next()) {
                double avgScore = rs3.getDouble("avg_score");
                if (rs3.wasNull()) {
                    jLabel4.setText("Average Score: N/A");
                } else {
                    jLabel4.setText(String.format("Average Score: %.1f%%", avgScore));
                }
            }
            rs3.close();
            ps3.close();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error loading stats: " + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
        // ========== QUIZZES CREATED TABLE ==========
    
    private void loadQuizzesCreated() {
        try {
            Connection conn = DBConnection.getConnection();
            int userId = AccountManager.getCurrentUserId();
            
            // Query quizzes created by user
            String query = "SELECT q.quiz_name, q.course, q.created_at, " +
                          "COUNT(r.response_id) as times_taken " +
                          "FROM quizzes q " +
                          "LEFT JOIN responses r ON q.quiz_id = r.quiz_id " +
                          "WHERE q.creator_id = ? " +
                          "GROUP BY q.quiz_id, q.quiz_name, q.course, q.created_at " +
                          "ORDER BY q.created_at DESC";
            
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setInt(1, userId);
            ResultSet rs = pst.executeQuery();
            
            // Create table model
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Clear existing rows
            
            // Set column names
            model.setColumnIdentifiers(new String[]{"Quiz Name", "Course", "Created Date", "Times Taken"});
            
            // Check if there's data
            boolean hasData = false;
            
            // Populate table
            while (rs.next()) {
                hasData = true;
                String quizName = rs.getString("quiz_name");
                String course = rs.getString("course");
                Timestamp createdAt = rs.getTimestamp("created_at");
                int timesTaken = rs.getInt("times_taken");
                
                // Format date
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MMM dd, yyyy");
                String formattedDate = sdf.format(createdAt);
                
                model.addRow(new Object[]{quizName, course, formattedDate, timesTaken});
            }
            
            if (!hasData) {
                model.addRow(new Object[]{"No quizzes created yet", "", "", ""});
            }
            
            rs.close();
            pst.close();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error loading created quizzes: " + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
       // ========== QUIZZES TAKEN TABLE ==========
    
    private void loadQuizzesTaken() {
        try {
            Connection conn = DBConnection.getConnection();
            int userId = AccountManager.getCurrentUserId();
            
            // Query quizzes taken by user
            String query = "SELECT q.quiz_name, q.course, r.completed_at, r.score " +
                          "FROM responses r " +
                          "JOIN quizzes q ON r.quiz_id = q.quiz_id " +
                          "WHERE r.user_id = ? " +
                          "ORDER BY r.completed_at DESC";
            
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setInt(1, userId);
            ResultSet rs = pst.executeQuery();
            
            // Create table model
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0); // Clear existing rows
            
            // Set column names
            model.setColumnIdentifiers(new String[]{"Quiz Name", "Course", "Date Taken", "Score"});
            
            // Check if there's data
            boolean hasData = false;
            
            // Populate table
            while (rs.next()) {
                hasData = true;
                String quizName = rs.getString("quiz_name");
                String course = rs.getString("course");
                Timestamp completedAt = rs.getTimestamp("completed_at");
                double score = rs.getDouble("score");
                
                // Format date
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MMM dd, yyyy HH:mm");
                String formattedDate = sdf.format(completedAt);
                
                model.addRow(new Object[]{quizName, course, formattedDate, String.format("%.1f%%", score)});
            }
            
            if (!hasData) {
                model.addRow(new Object[]{"No quizzes taken yet", "", "", ""});
            }
            
            rs.close();
            pst.close();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error loading taken quizzes: " + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
        private void loadPerformanceBySubject() {
        try {
            Connection conn = DBConnection.getConnection();
            int userId = AccountManager.getCurrentUserId();
            
            // Query average score by course
            String query = "SELECT q.course, AVG(r.score) as avg_score, COUNT(*) as quiz_count " +
                          "FROM responses r " +
                          "JOIN quizzes q ON r.quiz_id = q.quiz_id " +
                          "WHERE r.user_id = ? " +
                          "GROUP BY q.course " +
                          "ORDER BY avg_score DESC";
            
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setInt(1, userId);
            ResultSet rs = pst.executeQuery();
            
            StringBuilder performance = new StringBuilder();
            performance.append("╔════════════════════════════════════════╗\n");
            performance.append("║    PERFORMANCE BY SUBJECT              ║\n");
            performance.append("╚════════════════════════════════════════╝\n\n");
            
            boolean hasData = false;
            while (rs.next()) {
                hasData = true;
                String course = rs.getString("course");
                double avgScore = rs.getDouble("avg_score");
                int quizCount = rs.getInt("quiz_count");
                
                // Add emoji based on score
                String emoji;
                if (avgScore >= 90) {
                    emoji = "🏆"; // Excellent
                } else if (avgScore >= 80) {
                    emoji = "⭐"; // Great
                } else if (avgScore >= 70) {
                    emoji = "👍"; // Good
                } else if (avgScore >= 60) {
                    emoji = "📚"; // Pass
                } else {
                    emoji = "💪"; // Keep trying
                }
                
                performance.append(String.format("%s  %s\n", emoji, course));
                performance.append(String.format("     Average Score: %.1f%%\n", avgScore));
                performance.append(String.format("     Quizzes Taken: %d\n", quizCount));
                performance.append("     " + getProgressBar(avgScore) + "\n\n");
            }
            
            if (!hasData) {
                performance.append("No quiz data available yet.\n\n");
                performance.append("📝 Start taking quizzes to see your performance!\n");
                performance.append("💡 Track your progress across different subjects.\n");
                performance.append("🎯 Aim for higher scores and consistency!");
            }
            
            jTextArea1.setText(performance.toString());
            jTextArea1.setCaretPosition(0); // Scroll to top
            
            rs.close();
            pst.close();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error loading performance data: " + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    // Helper method to create progress bar
    private String getProgressBar(double score) {
        int filled = (int) (score / 10); // 10 blocks for 100%
        int empty = 10 - filled;
        
        StringBuilder bar = new StringBuilder("[");
        for (int i = 0; i < filled; i++) {
            bar.append("█");
        }
        for (int i = 0; i < empty; i++) {
            bar.append("░");
        }
        bar.append("]");
        
        return bar.toString();
    }
}
