/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.realeastprojectasin;
import java.io.*;
import java.net.*;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author gelo
 */
public class CHATBOT extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CHATBOT.class.getName());

    /**
     * Creates new form CHATBOT
     */
    public CHATBOT() {
        initComponents();
              setLocationRelativeTo(null);
                      // Welcome message
        appendMessage("Nova", "Hello! I'm your AI learning assistant. Ask me anything about your studies!");
        
        // Check if Flask is running
        checkServerStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChatDisplay = new javax.swing.JTextArea();
        lblInputPrompt = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        lblTitle.setText("NOVA");

        txtChatDisplay.setEditable(false);
        txtChatDisplay.setColumns(50);
        txtChatDisplay.setLineWrap(true);
        txtChatDisplay.setRows(20);
        txtChatDisplay.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtChatDisplay);

        lblInputPrompt.setText("Text:");

        jScrollPane2.setViewportView(jTextPane1);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Back");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(297, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblInputPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInputPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              String userMessage = jTextPane1.getText().trim();
        
        if (userMessage.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please type a message first!",
                "Empty Message",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Display user message
        appendMessage("You", userMessage);
        jTextPane1.setText(""); // Clear input field
        
        // Show typing indicator
        appendMessage("Nova", "Typing...");
        
        // Send to Flask in background thread (so UI doesn't freeze)
        new Thread(() -> {
            try {
                String aiResponse = sendToFlask(userMessage);
                
                // Update UI on main thread
                javax.swing.SwingUtilities.invokeLater(() -> {
                    removeLastMessage(); // Remove "Typing..."
                    appendMessage("Nova", aiResponse);
                });
                
            } catch (Exception e) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    removeLastMessage();
                    appendMessage("Error", "Failed to connect: " + e.getMessage());
                    appendMessage("System", "Make sure Flask is running in VSCode!");
                });
            }
        }).start();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CHATBOT().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblInputPrompt;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtChatDisplay;
    // End of variables declaration//GEN-END:variables
   private void checkServerStatus() {
        try {
            URL url = new URL("http://127.0.0.1:5000/ask");
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("POST");
            conn.setConnectTimeout(2000);
            conn.disconnect();
            
            appendMessage("System", "✅ Nova is online and ready!");
        } catch (Exception e) {
            appendMessage("System", "⚠️ Warning: Cannot connect to Nova. Make sure Flask is running in VSCode!");
        }
    }
      private String sendToFlask(String message) throws Exception {
        URL url = new URL("http://127.0.0.1:5000/ask");
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        
        // Setup request
        conn.setRequestMethod("POST");
        conn.setRequestProperty("Content-Type", "application/json");
        conn.setDoOutput(true);
        conn.setConnectTimeout(30000); // 30 second timeout
        conn.setReadTimeout(30000);
        
        // Create JSON: {"message": "user's question"}
        JSONObject payload = new JSONObject();
        payload.put("message", message);
        
        // Send request
        try (OutputStream os = conn.getOutputStream()) {
            byte[] input = payload.toString().getBytes("utf-8");
            os.write(input, 0, input.length);
        }
        
        // Read response
        int responseCode = conn.getResponseCode();
        
        if (responseCode == 200) {
            BufferedReader br = new BufferedReader(
                new InputStreamReader(conn.getInputStream(), "utf-8")
            );
            StringBuilder response = new StringBuilder();
            String line;
            while ((line = br.readLine()) != null) {
                response.append(line.trim());
            }
            br.close();
            
            // Parse JSON response: {"response": "Nova's answer"}
            JSONObject jsonResponse = new JSONObject(response.toString());
            return jsonResponse.getString("response");
        } else {
            throw new Exception("Server returned error code: " + responseCode);
        }
    }
        private void appendMessage(String sender, String message) {
        String timestamp = new java.text.SimpleDateFormat("HH:mm").format(new java.util.Date());
        String formattedMessage = String.format("[%s] %s: %s\n\n", timestamp, sender, message);
        
        txtChatDisplay.append(formattedMessage);
        
        // Auto-scroll to bottom
        txtChatDisplay.setCaretPosition(txtChatDisplay.getDocument().getLength());
    }
    
    // ========== REMOVE LAST MESSAGE (for typing indicator) ==========
    
    private void removeLastMessage() {
        String text = txtChatDisplay.getText();
        int lastIndex = text.lastIndexOf("[");
        if (lastIndex > 0) {
            txtChatDisplay.setText(text.substring(0, lastIndex));
        }
    }
}
