/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.realeastprojectasin;

import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.awt.Container;
/**
 *
 * @author gelo
 */
public class CREATEQUIZZES extends javax.swing.JFrame {
    
        private Connection connection;
    private List<QuestionPanel> questionPanels;
    private int questionCounter = 0;
    private JPanel questionsContainer;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CREATEQUIZZES.class.getName());

    /**
     * Creates new form CREATEQUIZZES
     */
    public CREATEQUIZZES() {
        initComponents();
            connection = DBConnection.getConnection();
    questionPanels = new ArrayList<>();
    
    // Setup the container panel inside scroll pane
    questionsContainer = new JPanel();
    questionsContainer.setLayout(new BoxLayout(questionsContainer, BoxLayout.Y_AXIS));
    jScrollPane1.setViewportView(questionsContainer);
    
    // Add first question automatically
    addQuestionPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(10, 38, 71));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel1.setText("Quiz Name:");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel2.setText("Course:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("CREATE QUIZ");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setText("Questions");

        jPanel1.setBackground(new java.awt.Color(10, 38, 71));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jButton1.setText("Add Question");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Cancel");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setText("Save Quiz");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
    int confirm = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to cancel?\n\nAll unsaved changes will be lost.",
        "Confirm Cancel",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE);
    
    if (confirm == JOptionPane.YES_OPTION) {
        this.dispose();
    }
     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    String quizName = jTextField1.getText().trim();
    String course = jTextField2.getText().trim();
    
    // VALIDATION
    if (quizName.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Please enter a quiz name!",
            "Missing Information",
            JOptionPane.WARNING_MESSAGE);
        jTextField1.requestFocus();
        return;
    }
    
    if (course.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Please enter a course!",
            "Missing Information",
            JOptionPane.WARNING_MESSAGE);
        jTextField2.requestFocus();
        return;
    }
    
    if (questionPanels.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Please add at least one question!",
            "No Questions",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Validate all questions are filled
    for (int i = 0; i < questionPanels.size(); i++) {
        QuestionPanel qp = questionPanels.get(i);
        if (!qp.isQuestionValid()) {
            JOptionPane.showMessageDialog(this,
                "Question " + (i + 1) + " is incomplete!\n\nPlease fill in all fields.",
                "Incomplete Question",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
    }
    
    // Save to database
    saveQuizToDatabase(quizName, course);

        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  addQuestionPanel();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CREATEQUIZZES().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
private void addQuestionPanel() {
    questionCounter++;
    
    // Create new question panel
    QuestionPanel qPanel = new QuestionPanel(questionCounter, this);
    questionPanels.add(qPanel);
    
    // Add to container with spacing
    questionsContainer.add(qPanel);
    questionsContainer.add(Box.createVerticalStrut(15));
    
    // Refresh display
    questionsContainer.revalidate();
    questionsContainer.repaint();
    
    // Auto-scroll to bottom
    SwingUtilities.invokeLater(() -> {
        JScrollBar vertical = jScrollPane1.getVerticalScrollBar();
        vertical.setValue(vertical.getMaximum());
    });
}
public void removeQuestionPanel(QuestionPanel panel) {
    if (questionPanels.size() <= 1) {
        JOptionPane.showMessageDialog(this,
            "Quiz must have at least one question!",
            "Cannot Remove",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    questionPanels.remove(panel);
    questionsContainer.remove(panel);
    
    // Renumber remaining questions
    for (int i = 0; i < questionPanels.size(); i++) {
        questionPanels.get(i).setQuestionNumber(i + 1);
    }
        
    questionCounter = questionPanels.size();
    
    questionsContainer.revalidate();
    questionsContainer.repaint();
}
private void saveQuizToDatabase(String quizName, String course) {
    try {
        connection.setAutoCommit(false);
        
        // 1. Insert quiz
        String insertQuiz = "INSERT INTO quizzes (quiz_name, course, creator_id, created_at) VALUES (?, ?, ?, NOW())";
        PreparedStatement ps = connection.prepareStatement(insertQuiz, Statement.RETURN_GENERATED_KEYS);
        ps.setString(1, quizName);
        ps.setString(2, course);
        ps.setInt(3, AccountManager.getCurrentUserId());
        ps.executeUpdate();
        
        // Get generated quiz_id
        ResultSet rs = ps.getGeneratedKeys();
        int quizId = 0;
        if (rs.next()) {
            quizId = rs.getInt(1);
        }
        
        // 2. Insert all questions
        String insertQuestion = "INSERT INTO questions (quiz_id, question_text, option_a, option_b, option_c, option_d, correct_answer) VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement ps2 = connection.prepareStatement(insertQuestion);
        
        for (QuestionPanel qp : questionPanels) {
            ps2.setInt(1, quizId);
            ps2.setString(2, qp.getQuestionText());
            ps2.setString(3, qp.getOptionA());
            ps2.setString(4, qp.getOptionB());
            ps2.setString(5, qp.getOptionC());
            ps2.setString(6, qp.getOptionD());
            ps2.setString(7, qp.getCorrectAnswer());
            ps2.executeUpdate();
        }
        
        // 3. Create notification
        String insertNotif = "INSERT INTO notifications (user_id, message, type, created_at, is_read) VALUES (?, ?, ?, NOW(), false)";
        PreparedStatement ps3 = connection.prepareStatement(insertNotif);
        ps3.setInt(1, AccountManager.getCurrentUserId());
        ps3.setString(2, "You created quiz: " + quizName);
        ps3.setString(3, "quiz_created");
        ps3.executeUpdate();
        
        // Commit transaction
        connection.commit();
        connection.setAutoCommit(true);
        
        // Success message
        JOptionPane.showMessageDialog(this,
            "Quiz Created Successfully!\n\n" +
            "Quiz: " + quizName + "\n" +
            "Course: " + course + "\n" +
            "Questions: " + questionPanels.size(),
            "Success",
            JOptionPane.INFORMATION_MESSAGE);
        
        // Close window
        this.dispose();
        
    } catch (SQLException e) {
        try {
            connection.rollback();
            connection.setAutoCommit(true);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
        JOptionPane.showMessageDialog(this,
            "Error saving quiz:\n" + e.getMessage(),
            "Database Error",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
// ============================================
// QUESTION PANEL CLASS
// ============================================
class QuestionPanel extends JPanel {
    
    private int questionNumber;
    private final CREATEQUIZZES parentFrame;
    
    private JLabel questionLabel;
    private JTextArea questionTextArea;
    private JTextField optionAField;
    private JTextField optionBField;
    private JTextField optionCField;
    private JTextField optionDField;
    private JComboBox<String> correctAnswerCombo;
    private JButton removeButton;
    
public QuestionPanel(int number, CREATEQUIZZES parent) {
    super(); // ✅ Explicitly call parent constructor first
    
    this.questionNumber = number;
    this.parentFrame = parent;
    
    // ✅ Initialize all fields to prevent null
    initializeFields();
    
    // ✅ Then setup UI
    setupUI();
}

// ✅ ADD THIS NEW METHOD
private void initializeFields() {
    questionTextArea = new JTextArea();
    optionAField = new JTextField();
    optionBField = new JTextField();
    optionCField = new JTextField();
    optionDField = new JTextField();
    correctAnswerCombo = new JComboBox<>(new String[]{"A", "B", "C", "D"});
    removeButton = new JButton("Remove");
    questionLabel = new JLabel();
}
    
 private void setupUI() {
    setLayout(null);
    setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(new Color(70, 130, 180), 2),
        BorderFactory.createEmptyBorder(10, 10, 10, 10)
    ));
    
    // ✅ ADJUSTED SIZE - Better fit
setPreferredSize(new Dimension(850, 320)); // matches screenshot width
setMaximumSize(new Dimension(850, 320));

    setBackground(new Color(30, 30, 40));
    
    // ========== TOP ROW: Question Number + Correct Answer + Remove ==========
    
    // Question number label
    questionLabel.setFont(new Font("Arial", Font.BOLD, 14));
    questionLabel.setForeground(Color.WHITE);
    questionLabel.setBounds(10, 5, 120, 25);
    questionLabel.setText("Question " + questionNumber + ":");
    add(questionLabel);
    
    // Correct answer label and combobox
    JLabel correctLabel = new JLabel("Correct:");
    correctLabel.setFont(new Font("Arial", Font.PLAIN, 12));
    correctLabel.setForeground(Color.WHITE);
    correctLabel.setBounds(140, 5, 60, 25);
    add(correctLabel);
    
    correctAnswerCombo.setBounds(200, 5, 60, 25);
    add(correctAnswerCombo);
    
    // Remove button
    removeButton.setBounds(310, 5, 90, 25);
    removeButton.setFont(new Font("Arial", Font.PLAIN, 11));
    removeButton.setFont(new Font("Arial", Font.PLAIN, 11));

// ✅ COMPLETE ACTION IN ONE PLACE:
removeButton.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        int confirm = JOptionPane.showConfirmDialog(
            CREATEQUIZZES.this,
            "Remove this question?",
            "Confirm",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {

            // 1️⃣ Cast parent to your custom QuestionPanel class
            QuestionPanel qp = (QuestionPanel) removeButton.getParent();

            // 2️⃣ Remove from ArrayList (IMPORTANT)
            questionPanels.remove(qp);

            // 3️⃣ Remove from UI
            Container parent = qp.getParent();
            parent.remove(qp);
            parent.revalidate();
            parent.repaint();

            // 4️⃣ Renumber the remaining questions
            renumberQuestions();
        }
    }
});


add(removeButton);
 
    
    
    // ========== QUESTION TEXT AREA ==========
    
    JLabel qTextLabel = new JLabel("Question:");
    qTextLabel.setFont(new Font("Arial", Font.PLAIN, 12));
    qTextLabel.setForeground(Color.WHITE);
    qTextLabel.setBounds(10, 35, 100, 20);
    add(qTextLabel);
    
    questionTextArea.setLineWrap(true);
    questionTextArea.setWrapStyleWord(true);
    questionTextArea.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    questionTextArea.setFont(new Font("Arial", Font.PLAIN, 12));
    JScrollPane qScrollPane = new JScrollPane(questionTextArea);
    qScrollPane.setBounds(10, 60, 390, 50);
    add(qScrollPane);
    
    // ========== OPTIONS A, B, C, D ==========
    
    // Option A
    JLabel optionALabel = new JLabel("A)");
    optionALabel.setFont(new Font("Arial", Font.BOLD, 12));
    optionALabel.setForeground(Color.WHITE);
    optionALabel.setBounds(10, 120, 25, 25);
    add(optionALabel);
    
    optionAField.setBounds(35, 120, 365, 25);
    optionAField.setFont(new Font("Arial", Font.PLAIN, 12));
    add(optionAField);
    
    // Option B
    JLabel optionBLabel = new JLabel("B)");
    optionBLabel.setFont(new Font("Arial", Font.BOLD, 12));
    optionBLabel.setForeground(Color.WHITE);
    optionBLabel.setBounds(10, 155, 25, 25);
    add(optionBLabel);
    
    optionBField.setBounds(35, 155, 365, 25);
    optionBField.setFont(new Font("Arial", Font.PLAIN, 12));
    add(optionBField);
    
    // Option C
    JLabel optionCLabel = new JLabel("C)");
    optionCLabel.setFont(new Font("Arial", Font.BOLD, 12));
    optionCLabel.setForeground(Color.WHITE);
    optionCLabel.setBounds(10, 190, 25, 25);
    add(optionCLabel);
    
    optionCField.setBounds(35, 190, 365, 25);
    optionCField.setFont(new Font("Arial", Font.PLAIN, 12));
    add(optionCField);
    
    // Option D
    JLabel optionDLabel = new JLabel("D)");
    optionDLabel.setFont(new Font("Arial", Font.BOLD, 12));
    optionDLabel.setForeground(Color.WHITE);
    optionDLabel.setBounds(10, 225, 25, 25);
    add(optionDLabel);
    
    optionDField.setBounds(35, 225, 365, 25);
    optionDField.setFont(new Font("Arial", Font.PLAIN, 12));
    add(optionDField);
}
   
    // Getters
    public String getQuestionText() {
        return questionTextArea.getText().trim();
    }
    
    public String getOptionA() {
        return optionAField.getText().trim();
    }
    
    public String getOptionB() {
        return optionBField.getText().trim();
    }
    
    public String getOptionC() {
        return optionCField.getText().trim();
    }
    
    public String getOptionD() {
        return optionDField.getText().trim();
    }
    
    public String getCorrectAnswer() {
        return correctAnswerCombo.getSelectedItem().toString();
    }
    
    public void setQuestionNumber(int number) {
        this.questionNumber = number;
        questionLabel.setText("Question " + number);
    }
    
    public boolean isQuestionValid() {
        return !getQuestionText().isEmpty() &&
               !getOptionA().isEmpty() &&
               !getOptionB().isEmpty() &&
               !getOptionC().isEmpty() &&
               !getOptionD().isEmpty();
    }
}
private void removeQuestion(JButton removeButton) {
    // Confirm deletion
    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Remove this question?",
        "Confirm",
        JOptionPane.YES_NO_OPTION
    );
    
    if (confirm == JOptionPane.YES_OPTION) {
        // Get the panel containing the remove button
        Container questionPanel = removeButton.getParent();
        Container container = questionPanel.getParent();
        
        // Remove it
        container.remove(questionPanel);
        container.revalidate();
        container.repaint();
        
        JOptionPane.showMessageDialog(this, "Question removed!");
    }
}
private void renumberQuestions() {
    for (int i = 0; i < questionPanels.size(); i++) {
        QuestionPanel qp = questionPanels.get(i);

        qp.setBorder(
            BorderFactory.createTitledBorder("Question " + (i + 1))
        );

        qp.repaint();
    }
}

}
