/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.realeastprojectasin;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/** 
 *
 * @author gelo
 */
public class FIRSTLOADING extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FIRSTLOADING.class.getName());

    /**
     * Creates new form FIRSTLOADING
     */
    public FIRSTLOADING() {
        initComponents();
        setLocationRelativeTo(null);
        loading();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 710, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("100%");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, -1, -1));

        jLabel3.setBackground(java.awt.SystemColor.activeCaption);
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Loading...");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 70, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainpicreal.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
try {
        // Apply FlatLaf *before* any GUI forms are created
        UIManager.setLookAndFeel(new FlatMacDarkLaf());

        // Nova blue theme customization
        UIManager.put("Component.arc", 20);
        UIManager.put("Button.arc", 25);
        UIManager.put("ProgressBar.arc", 999);
        UIManager.put("Panel.background", new java.awt.Color(0x0A192F)); // dark blue
        UIManager.put("Label.foreground", java.awt.Color.WHITE);
        UIManager.put("Button.foreground", java.awt.Color.WHITE);
        UIManager.put("Button.background", new java.awt.Color(0x2196F3)); // light blue accent
        UIManager.put("TextComponent.arc", 10);

    } catch (UnsupportedLookAndFeelException e) {
        e.printStackTrace();
    }

    // Run the form
    java.awt.EventQueue.invokeLater(() -> {
        new FIRSTLOADING().setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    
    private void loading() {
    new Thread(new Runnable() {
        @Override
        public void run() {
            try {
                for (int i = 0; i <= 100; i++) {
                    // Update progress bar
                    jProgressBar1.setValue(i);

                    // Update labels dynamically
                    jLabel2.setText(i + "%");  // shows 0% → 100%
                    jLabel3.setText("Loading...");

                    Thread.sleep(50); // speed of progress
                }

                // After loading completes
                jLabel3.setText("Done!");
                Thread.sleep(500); // short pause before next action

                // Switch to LOGIN frame
                LOGIN loginFrame = new LOGIN();
                loginFrame.setVisible(true);

                // Close (dispose) this loading screen
                dispose();

            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }).start();
}
}
