/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.realeastprojectasin;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import java.awt.BorderLayout;

/**
 *
 * @author gelo
 */
public class MAIN extends javax.swing.JFrame {
        private Connection connection;
    
    // Stats variables
    private int quizzesCreated = 0;
    private int quizzesTaken = 0;
    private double averageScore = 0.0;
    private int streakDays = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MAIN.class.getName());

    /**
     * Creates new form MAIN
     */
    public MAIN() {
        initComponents();
        setLocationRelativeTo(null);
            jLabel1.setText("Welcome, " + AccountManager.getCurrentUsername() + "!");
    
   
    loadNotifications();
     loadStreak();
      loadPerformanceChart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chartPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        notificationsPanel = new javax.swing.JPanel();
        lblNotificationsTitle = new javax.swing.JLabel();
        notificationsScrollPane = new javax.swing.JScrollPane();
        notificationsTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jLabel1.setText("Hello");

        chartPanel.setBackground(new java.awt.Color(153, 255, 0));
        chartPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("jLabel2");
        chartPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(10, 38, 71));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("View Quizzes");
        jButton1.setPreferredSize(new java.awt.Dimension(92, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Create Quiz");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        notificationsPanel.setBackground(new java.awt.Color(10, 38, 71));

        lblNotificationsTitle.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblNotificationsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotificationsTitle.setText("Recent Activities");

        notificationsTextArea.setEditable(false);
        notificationsTextArea.setColumns(20);
        notificationsTextArea.setLineWrap(true);
        notificationsTextArea.setRows(5);
        notificationsTextArea.setWrapStyleWord(true);
        notificationsScrollPane.setViewportView(notificationsTextArea);

        javax.swing.GroupLayout notificationsPanelLayout = new javax.swing.GroupLayout(notificationsPanel);
        notificationsPanel.setLayout(notificationsPanelLayout);
        notificationsPanelLayout.setHorizontalGroup(
            notificationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notificationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notificationsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notificationsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNotificationsTitle)
                .addGap(89, 89, 89))
        );
        notificationsPanelLayout.setVerticalGroup(
            notificationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notificationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNotificationsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notificationsScrollPane)
                .addContainerGap())
        );

        jMenuBar1.setToolTipText("");
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("Dashboard");
        jMenu1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Profile");
        jMenu3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N

        jMenuItem3.setText("Personal Account");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Overall Stats");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);
        jMenu3.add(jSeparator1);

        jMenuItem1.setText("Friends");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Achievements");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Settings");
        jMenu4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N

        jMenuItem10.setText("Security");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem7.setText("Logout");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);
        jMenu4.add(jSeparator2);

        jMenuItem5.setText("Calendar");
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Chatbot");
        jMenu2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notificationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(notificationsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        setSize(new java.awt.Dimension(944, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        new FIRSTLOADING().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        new SECURITY().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new PERSONALACC().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new ALLSTATS().setVisible(true);
               // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             new VIEWQUIZ().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             new CREATEQUIZZES().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        new MAIN().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        new CHATBOT().setVisible(true);
              // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
         new CHATBOT().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
int confirm = JOptionPane.showConfirmDialog(
        this,
        "Open Friends List?\n\nThis feature is still in development.",
        "Friends",
        JOptionPane.YES_NO_OPTION
);

if (confirm == JOptionPane.YES_OPTION) {
    JOptionPane.showMessageDialog(
            this,
            "Friends feature coming soon!\n\n" +
            "You'll be able to add, view, and chat with friends here.",
            "Feature In Progress",
            JOptionPane.INFORMATION_MESSAGE
    );

    // When FRIENDS feature is ready:
    // new FriendsFrame().setVisible(true);
    // this.dispose();
}

    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Open Achievements?\n\nThis feature is still in development.",
        "Achievements",
        JOptionPane.YES_NO_OPTION
);

if (confirm == JOptionPane.YES_OPTION) {
    JOptionPane.showMessageDialog(
            this,
            "Friends feature coming soon!\n\n" +
            "You'll be able to view your achievements here.",
            "Feature In Progress",
            JOptionPane.INFORMATION_MESSAGE
    );

    // When FRIENDS feature is ready:
    // new FriendsFrame().setVisible(true);
    // this.dispose();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
          int confirm = JOptionPane.showConfirmDialog(
        this,
        "Open Achievements?\n\nThis feature is still in development.",
        "Achievements",
        JOptionPane.YES_NO_OPTION
);

if (confirm == JOptionPane.YES_OPTION) {
    JOptionPane.showMessageDialog(
            this,
            "Friends feature coming soon!\n\n" +
            "You'll be able to view your achievements here.",
            "Feature In Progress",
            JOptionPane.INFORMATION_MESSAGE
    );

    // When FRIENDS feature is ready:
    // new FriendsFrame().setVisible(true);
    // this.dispose();
}
       // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
           int confirm = JOptionPane.showConfirmDialog(
        this,
        "Open Friends List?\n\nThis feature is still in development.",
        "Friends",
        JOptionPane.YES_NO_OPTION
);

if (confirm == JOptionPane.YES_OPTION) {
    JOptionPane.showMessageDialog(
            this,
            "Friends feature coming soon!\n\n" +
            "You'll be able to add, view, and chat with friends here.",
            "Feature In Progress",
            JOptionPane.INFORMATION_MESSAGE
    );

    // When FRIENDS feature is ready:
    // new FriendsFrame().setVisible(true);
    // this.dispose();
}
 // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MAIN().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblNotificationsTitle;
    private javax.swing.JPanel notificationsPanel;
    private javax.swing.JScrollPane notificationsScrollPane;
    private javax.swing.JTextArea notificationsTextArea;
    // End of variables declaration//GEN-END:variables

private void loadNotifications() {
    try {
        Connection conn = DBConnection.getConnection();
        
        // Use AccountManager.getCurrentUserId() - matches your pattern
        int userId = AccountManager.getCurrentUserId();
        
        String query = "SELECT message, type, created_at " +
                      "FROM notifications " +
                      "WHERE user_id = ? " +
                      "ORDER BY created_at DESC " +
                      "LIMIT 10";
        
        PreparedStatement pst = conn.prepareStatement(query);
        pst.setInt(1, userId);
        
        ResultSet rs = pst.executeQuery();
        
        if (!rs.isBeforeFirst()) {
            notificationsTextArea.setText("No notifications yet.\n\nCreate or take a quiz to get started!");
            return;
        }
        
        StringBuilder notifText = new StringBuilder();
        
        while (rs.next()) {
            String message = rs.getString("message");
            String type = rs.getString("type");
            Timestamp createdAt = rs.getTimestamp("created_at");
            
            String icon = getNotificationIcon(type);
            String timeAgo = calculateTimeAgo(createdAt);
            
            notifText.append(icon).append(" ").append(message).append("\n");
            notifText.append("   ").append(timeAgo).append("\n");
            notifText.append("   ─────────────────────\n\n");
        }
        
        notificationsTextArea.setText(notifText.toString());
        notificationsTextArea.setCaretPosition(0);
        
        rs.close();
        pst.close();
        
    } catch (SQLException e) {
        notificationsTextArea.setText("Error loading notifications.\n\n" + e.getMessage());
        logger.log(java.util.logging.Level.SEVERE, "Error loading notifications", e);
    }
}

private String getNotificationIcon(String type) {
    switch (type.toLowerCase()) {
        case "quiz_created":
            return "🔔";
        case "quiz_completed":
            return "✅";
        case "quiz_available":
            return "📝";
        case "achievement":
            return "🏆";
        case "reminder":
            return "⏰";
        default:
            return "📌";
    }
}

private String calculateTimeAgo(Timestamp timestamp) {
    long currentTime = System.currentTimeMillis();
    long notificationTime = timestamp.getTime();
    
    long diffMillis = currentTime - notificationTime;
    long diffSeconds = diffMillis / 1000;
    long diffMinutes = diffSeconds / 60;
    long diffHours = diffMinutes / 60;
    long diffDays = diffHours / 24;
    
    if (diffDays > 0) {
        return diffDays + (diffDays == 1 ? " day ago" : " days ago");
    } else if (diffHours > 0) {
        return diffHours + (diffHours == 1 ? " hour ago" : " hours ago");
    } else if (diffMinutes > 0) {
        return diffMinutes + (diffMinutes == 1 ? " minute ago" : " minutes ago");
    } else {
        return "Just now";
    }
}
private void loadStreak() {
    try {
        Connection conn = DBConnection.getConnection();
        int userId = AccountManager.getCurrentUserId();
        
        // Get all distinct quiz completion dates, ordered by most recent
        String query = "SELECT DISTINCT DATE(completed_at) as quiz_date " +
                      "FROM responses " +
                      "WHERE user_id = ? " +
                      "ORDER BY quiz_date DESC";
        
        PreparedStatement pst = conn.prepareStatement(query);
        pst.setInt(1, userId);
        ResultSet rs = pst.executeQuery();
        
        // Calculate streak
        int streak = 0;
        java.sql.Date previousDate = null;
        java.sql.Date today = new java.sql.Date(System.currentTimeMillis());
        
        while (rs.next()) {
            java.sql.Date quizDate = rs.getDate("quiz_date");
            
            if (previousDate == null) {
                // First iteration - check if quiz was taken today or yesterday
                long daysDiff = (today.getTime() - quizDate.getTime()) / (1000 * 60 * 60 * 24);
                
                if (daysDiff > 1) {
                    // Streak is broken - no quiz today or yesterday
                    break;
                }
                
                streak = 1;
                previousDate = quizDate;
            } else {
                // Check if this date is exactly 1 day before previous date
                long daysDiff = (previousDate.getTime() - quizDate.getTime()) / (1000 * 60 * 60 * 24);
                
                if (daysDiff == 1) {
                    streak++;
                    previousDate = quizDate;
                } else {
                    // Gap found - streak broken
                    break;
                }
            }
        }
        
        // Update streak display
        streakDays = streak;
        updateStreakDisplay();
        
        rs.close();
        pst.close();
        
    } catch (SQLException e) {
        logger.log(java.util.logging.Level.SEVERE, "Error calculating streak", e);
        streakDays = 0;
        updateStreakDisplay();
    }
}

private void updateStreakDisplay() {
    // Update your streak label (adjust the label name to match yours)
    // Looking at your image, it seems to be the "🔥 100 DAY STREAK" area
    
    if (streakDays == 0) {
        jLabel5.setText("START YOUR STREAK!");  // Change jLabel6 to your actual streak label name
    } else if (streakDays == 1) {
        jLabel5.setText(streakDays + " DAY STREAK");
    } else {
        jLabel5.setText(streakDays + " DAY STREAK!");
    }
    
    // Optional: Add color coding based on streak
    if (streakDays >= 30) {
        jLabel5.setForeground(new java.awt.Color(255, 0, 0)); // Red/Gold
    } else if (streakDays >= 7) {
        jLabel5.setForeground(new java.awt.Color(255, 140, 0)); // Orange
    } else if (streakDays > 0) {
        jLabel5.setForeground(new java.awt.Color(255, 215, 0)); // Yellow
    } else {
        jLabel5.setForeground(new java.awt.Color(128, 128, 128)); // Gray
    }
}
private void loadPerformanceChart() {
    try {
        Connection conn = DBConnection.getConnection();
        int userId = AccountManager.getCurrentUserId();
        
        // Query to get quiz performance data
        String query = "SELECT q.quiz_name, q.course, r.score, r.completed_at " +
                      "FROM responses r " +
                      "JOIN quizzes q ON r.quiz_id = q.quiz_id " +
                      "WHERE r.user_id = ? " +
                      "ORDER BY r.completed_at ASC " +
                      "LIMIT 20"; // Show last 20 quizzes
        
        PreparedStatement pst = conn.prepareStatement(query);
        pst.setInt(1, userId);
        ResultSet rs = pst.executeQuery();
        
        // Create dataset
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        int quizCount = 0;
        double totalScore = 0;
        double minScore = 100;
        double maxScore = 0;
        
        // Store data for calculations
        java.util.List<Double> scores = new java.util.ArrayList<>();
        java.util.List<String> quizLabels = new java.util.ArrayList<>();
        
        while (rs.next()) {
            String quizName = rs.getString("quiz_name");
            double score = rs.getDouble("score");
            quizCount++;
            
            scores.add(score);
            quizLabels.add("Q" + quizCount); // Simple labels: Q1, Q2, Q3...
            
            totalScore += score;
            if (score < minScore) minScore = score;
            if (score > maxScore) maxScore = score;
            
            // Add your actual score
            dataset.addValue(score, "Your Score", "Q" + quizCount);
        }
        
        rs.close();
        pst.close();
        
        // Add additional data series if there's data
        if (quizCount > 0) {
            double avgScore = totalScore / quizCount;
            
            // Add average line (constant across all quizzes)
            for (int i = 1; i <= quizCount; i++) {
                dataset.addValue(avgScore, "Average", "Q" + i);
            }
            
            // Add passing line (70% threshold)
            for (int i = 1; i <= quizCount; i++) {
                dataset.addValue(70, "Passing Grade (70%)", "Q" + i);
            }
            
            // Add target line (90% excellence)
            for (int i = 1; i <= quizCount; i++) {
                dataset.addValue(90, "Excellence (90%)", "Q" + i);
            }
        }
        
        // Create chart
        JFreeChart chart;
        
        if (quizCount == 0) {
            // No data - create empty chart with message
            dataset.addValue(0, "No Data", "Start");
            chart = ChartFactory.createLineChart(
                "Take quizzes to see your performance!",
                "Quiz Number",
                "Score (%)",
                dataset,
                PlotOrientation.VERTICAL,
                false,
                false,
                false
            );
        } else {
            // Create actual chart
            chart = ChartFactory.createLineChart(
                "Your Quiz Performance Over Time",
                "Quiz Number",
                "Score (%)",
                dataset,
                PlotOrientation.VERTICAL,
                true,  // Show legend
                true,  // Show tooltips
                false  // No URLs
            );
        }
        
        // Customize chart appearance
        chart.setBackgroundPaint(java.awt.Color.WHITE);
        
        // Get the plot
        org.jfree.chart.plot.CategoryPlot plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(new java.awt.Color(245, 245, 245));
        plot.setDomainGridlinePaint(java.awt.Color.LIGHT_GRAY);
        plot.setRangeGridlinePaint(java.awt.Color.LIGHT_GRAY);
        
        // LOCK Y-AXIS to 0-100 range (no scrolling needed)
        org.jfree.chart.axis.ValueAxis rangeAxis = plot.getRangeAxis();
        rangeAxis.setRange(0, 100);
        rangeAxis.setAutoRange(false); // ✅ DISABLE auto-range
        rangeAxis.setLowerBound(0);    // ✅ LOCK to 0
        rangeAxis.setUpperBound(100);  // ✅ LOCK to 100
        
        // Customize line colors
        org.jfree.chart.renderer.category.LineAndShapeRenderer renderer = 
            (org.jfree.chart.renderer.category.LineAndShapeRenderer) plot.getRenderer();
        
        // Your Score - Blue, thick line with shapes
        renderer.setSeriesPaint(0, new java.awt.Color(33, 150, 243)); // Blue
        renderer.setSeriesStroke(0, new java.awt.BasicStroke(3.0f));
        renderer.setSeriesShapesVisible(0, true);
        
        if (quizCount > 0) {
            // Your Average - Green, dashed line
            renderer.setSeriesPaint(1, new java.awt.Color(76, 175, 80)); // Green
            renderer.setSeriesStroke(1, new java.awt.BasicStroke(
                2.0f, java.awt.BasicStroke.CAP_BUTT, java.awt.BasicStroke.JOIN_MITER,
                10.0f, new float[]{10.0f}, 0.0f)); // Dashed
            renderer.setSeriesShapesVisible(1, false);
            
            // Passing Grade - Orange, dashed line
            renderer.setSeriesPaint(2, new java.awt.Color(255, 152, 0)); // Orange
            renderer.setSeriesStroke(2, new java.awt.BasicStroke(
                1.5f, java.awt.BasicStroke.CAP_BUTT, java.awt.BasicStroke.JOIN_MITER,
                10.0f, new float[]{5.0f}, 0.0f)); // Dashed
            renderer.setSeriesShapesVisible(2, false);
            
            // Excellence - Red, dashed line
            renderer.setSeriesPaint(3, new java.awt.Color(244, 67, 54)); // Red
            renderer.setSeriesStroke(3, new java.awt.BasicStroke(
                1.5f, java.awt.BasicStroke.CAP_BUTT, java.awt.BasicStroke.JOIN_MITER,
                10.0f, new float[]{5.0f}, 0.0f)); // Dashed
            renderer.setSeriesShapesVisible(3, false);
        }
        
        // Create ChartPanel with NO ZOOM/SCROLL features
        ChartPanel chartPanelComponent = new ChartPanel(chart);
        chartPanelComponent.setPreferredSize(new java.awt.Dimension(800, 400));
        
        // ✅ DISABLE all zoom and scroll features
        chartPanelComponent.setMouseZoomable(false);
        chartPanelComponent.setMouseWheelEnabled(false);
        chartPanelComponent.setDomainZoomable(false);
        chartPanelComponent.setRangeZoomable(false);
        
        // Clear existing components and add chart
        chartPanel.removeAll();
        chartPanel.setLayout(new BorderLayout());
        chartPanel.add(chartPanelComponent, BorderLayout.CENTER);
        chartPanel.validate();
        chartPanel.repaint();
        
    } catch (SQLException e) {
        logger.log(java.util.logging.Level.SEVERE, "Error loading chart", e);
        
        // Show error message in chart panel
        javax.swing.JLabel errorLabel = new javax.swing.JLabel(
            "<html><center>Err<br>" + 
            e.getMessage() + "</center></html>"
        );
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chartPanel.removeAll();
        chartPanel.add(errorLabel, BorderLayout.CENTER);
        chartPanel.validate();
    }
}
}
