/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.realeastprojectasin;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author gelo
 */
public class SECURITY extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SECURITY.class.getName());

    /**
     * Creates new form SECURITY
     */
    public SECURITY() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        jLabel1.setText("User and password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel2.setText("CHANGE USERNAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel3.setText("CHANGE PASSWORD");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 216, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Current Username:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("New Username:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("Current Password:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("New Password:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setText("Confirm Password:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 170, -1));

        jScrollPane2.setViewportView(jTextPane2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, -1));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 172, -1));
        jPanel1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 172, -1));
        jPanel1.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 172, -1));

        jCheckBox1.setText("Show pass to all");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 120, 20));

        jLabel9.setText("Back");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("DELETE ACCOUNT");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       if (jCheckBox1.isSelected()) {
        jPasswordField1.setEchoChar((char) 0);
        jPasswordField2.setEchoChar((char) 0);
        jPasswordField3.setEchoChar((char) 0);
    } else {
        jPasswordField1.setEchoChar('●');
        jPasswordField2.setEchoChar('●');
        jPasswordField3.setEchoChar('●');
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String currentUsername = jTextPane1.getText().trim();
        String newUsername = jTextPane2.getText().trim();
        
        // Validation
        if (currentUsername.isEmpty() || newUsername.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please fill in all username fields.",
                "Input Required",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Check if new username is different
        if (currentUsername.equals(newUsername)) {
            JOptionPane.showMessageDialog(this,
                "New username must be different from current username.",
                "Invalid Input",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Verify current username matches
        try {
            Connection conn = DBConnection.getConnection();
            int userId = AccountManager.getCurrentUserId();
            
            // Verify current username
            String verifyQuery = "SELECT username FROM users WHERE user_id = ?";
            PreparedStatement verifyPst = conn.prepareStatement(verifyQuery);
            verifyPst.setInt(1, userId);
            ResultSet rs = verifyPst.executeQuery();
            
            if (rs.next()) {
                String actualUsername = rs.getString("username");
                
                if (!actualUsername.equals(currentUsername)) {
                    JOptionPane.showMessageDialog(this,
                        "Current username is incorrect.",
                        "Verification Failed",
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            
            rs.close();
            verifyPst.close();
            
            // Check if new username already exists
            String checkQuery = "SELECT user_id FROM users WHERE username = ? AND user_id != ?";
            PreparedStatement checkPst = conn.prepareStatement(checkQuery);
            checkPst.setString(1, newUsername);
            checkPst.setInt(2, userId);
            ResultSet checkRs = checkPst.executeQuery();
            
            if (checkRs.next()) {
                JOptionPane.showMessageDialog(this,
                    "Username already taken. Please choose another.",
                    "Username Exists",
                    JOptionPane.ERROR_MESSAGE);
                checkRs.close();
                checkPst.close();
                return;
            }
            
            checkRs.close();
            checkPst.close();
            
            // Update username
            String updateQuery = "UPDATE users SET username = ? WHERE user_id = ?";
            PreparedStatement updatePst = conn.prepareStatement(updateQuery);
            updatePst.setString(1, newUsername);
            updatePst.setInt(2, userId);
            
            int rowsAffected = updatePst.executeUpdate(); // ✅ Use executeUpdate() not executeQuery()
            
            if (rowsAffected > 0) {
                // Update AccountManager
                AccountManager.setCurrentUsername(newUsername);
                
                JOptionPane.showMessageDialog(this,
                    "Username changed successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                
                // Clear fields
                jTextPane1.setText("");
                jTextPane2.setText("");
            } else {
                JOptionPane.showMessageDialog(this,
                    "Failed to update username.",
                    "Update Failed",
                    JOptionPane.ERROR_MESSAGE);
            }
            
            updatePst.close();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Database error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String currentPassword = new String(jPasswordField1.getPassword()).trim();
    String newPassword = new String(jPasswordField2.getPassword()).trim();
    String confirmPassword = new String(jPasswordField3.getPassword()).trim();

    if (currentPassword.isEmpty() || newPassword.isEmpty() || confirmPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all password fields.");
        return;
    }

    if (!newPassword.equals(confirmPassword)) {
        JOptionPane.showMessageDialog(this, "New password and confirmation do not match.");
        return;
    }

    if (newPassword.length() < 6) {
        JOptionPane.showMessageDialog(this, "New password must be at least 6 characters!");
        return;
    }

    try {
        Connection conn = DBConnection.getConnection();
        int userId = AccountManager.getCurrentUserId();

        // Fetch current stored password (hashed or plain)
        String sql = "SELECT password FROM users WHERE user_id = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, userId);
        ResultSet rs = pst.executeQuery();

        if (!rs.next()) {
            JOptionPane.showMessageDialog(this, "User not found!");
            return;
        }

        String storedPassword = rs.getString("password");

        // Correct checking method
        if (!PasswordUtils.matches(currentPassword, storedPassword)) {
            JOptionPane.showMessageDialog(this, "Current password is incorrect!");
            return;
        }

        // Hash new password before saving
        String newHashed = PasswordUtils.hash(newPassword);

        String updateSql = "UPDATE users SET password = ? WHERE user_id = ?";
        PreparedStatement updatePst = conn.prepareStatement(updateSql);
        updatePst.setString(1, newHashed);
        updatePst.setInt(2, userId);

        int updated = updatePst.executeUpdate();

        if (updated > 0) {
            JOptionPane.showMessageDialog(this, "Password changed successfully!");
            jPasswordField1.setText("");
            jPasswordField2.setText("");
            jPasswordField3.setText("");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
    this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
     int confirm1 = JOptionPane.showConfirmDialog(this,
        "⚠️ WARNING: ACCOUNT DELETION ⚠️\n\n" +
        "You are about to DELETE your account permanently.\n\n" +
        "This will delete:\n" +
        "• Your account information\n" +
        "• All quizzes you created\n" +
        "• All your quiz responses\n" +
        "• All your notifications\n" +
        "• All your statistics\n\n" +
        "Are you absolutely sure?",
        "Delete Account - Warning",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE);
    
    if (confirm1 != JOptionPane.YES_OPTION) {
        return;
    }
    
    // Step 2: Create custom panel for username and password input
    JPanel panel = new JPanel(new GridLayout(2, 2, 10, 10));
    
    JLabel lblUsername = new JLabel("Username:");
    JTextField txtUsername = new JTextField(20);
    
    JLabel lblPassword = new JLabel("Password:");
    JPasswordField txtPassword = new JPasswordField(20);
    
    panel.add(lblUsername);
    panel.add(txtUsername);
    panel.add(lblPassword);
    panel.add(txtPassword);
    
    int result = JOptionPane.showConfirmDialog(this, panel,
        "Verify Your Identity",
        JOptionPane.OK_CANCEL_OPTION,
        JOptionPane.PLAIN_MESSAGE);
    
    if (result != JOptionPane.OK_OPTION) {
        JOptionPane.showMessageDialog(this,
            "Account deletion cancelled.",
            "Cancelled",
            JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    String inputUsername = txtUsername.getText().trim();
    String inputPassword = new String(txtPassword.getPassword()).trim();
    
    if (inputUsername.isEmpty() || inputPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Username and password are required!",
            "Input Required",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Step 3: Verify credentials
   try {
    Connection conn = DBConnection.getConnection();
    int userId = AccountManager.getCurrentUserId();
        
    String verifyQuery = "SELECT username, password FROM users WHERE user_id = ?";
    PreparedStatement verifyPst = conn.prepareStatement(verifyQuery);
    verifyPst.setInt(1, userId);
    ResultSet rs = verifyPst.executeQuery();
        
    if (rs.next()) {
        String actualUsername = rs.getString("username");
        String actualPassword = rs.getString("password");

        // username must match
        if (!actualUsername.equals(inputUsername)) {
            JOptionPane.showMessageDialog(this, "Incorrect username!");
            return;
        }

        // password must match (hashed or plaintext)
        if (!PasswordUtils.matches(inputPassword, actualPassword)) {
            JOptionPane.showMessageDialog(this, "Incorrect password!");
            return;
        }
    }
        
    rs.close();
    verifyPst.close();
        
        // Step 4: Final confirmation
        int confirm2 = JOptionPane.showConfirmDialog(this,
            "⚠️ FINAL WARNING ⚠️\n\n" +
            "This is your LAST CHANCE!\n\n" +
            "Click YES to permanently delete your account.\n" +
            "Click NO to cancel and keep your account.\n\n" +
            "There is NO UNDO for this action!",
            "Final Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.ERROR_MESSAGE);
        
        if (confirm2 != JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this,
                "Account deletion cancelled.\n\n" +
                "Your account is safe!",
                "Cancelled",
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        // Step 5: Delete everything (in correct order to respect foreign keys)
        
        // Delete user_answers for this user's responses
        String deleteAnswersQuery = "DELETE FROM user_answers WHERE response_id IN " +
                                   "(SELECT response_id FROM responses WHERE user_id = ?)";
        PreparedStatement pst1 = conn.prepareStatement(deleteAnswersQuery);
        pst1.setInt(1, userId);
        pst1.executeUpdate();
        pst1.close();
        
        // Delete responses
        String deleteResponsesQuery = "DELETE FROM responses WHERE user_id = ?";
        PreparedStatement pst2 = conn.prepareStatement(deleteResponsesQuery);
        pst2.setInt(1, userId);
        pst2.executeUpdate();
        pst2.close();
        
        // Delete notifications
        String deleteNotifsQuery = "DELETE FROM notifications WHERE user_id = ?";
        PreparedStatement pst3 = conn.prepareStatement(deleteNotifsQuery);
        pst3.setInt(1, userId);
        pst3.executeUpdate();
        pst3.close();
        
        // Delete questions from user's quizzes
        String deleteQuestionsQuery = "DELETE FROM questions WHERE quiz_id IN " +
                                     "(SELECT quiz_id FROM quizzes WHERE creator_id = ?)";
        PreparedStatement pst4 = conn.prepareStatement(deleteQuestionsQuery);
        pst4.setInt(1, userId);
        pst4.executeUpdate();
        pst4.close();
        
        // Delete quizzes
        String deleteQuizzesQuery = "DELETE FROM quizzes WHERE creator_id = ?";
        PreparedStatement pst5 = conn.prepareStatement(deleteQuizzesQuery);
        pst5.setInt(1, userId);
        pst5.executeUpdate();
        pst5.close();
        
        // Finally, delete user account
        String deleteUserQuery = "DELETE FROM users WHERE user_id = ?";
        PreparedStatement pst6 = conn.prepareStatement(deleteUserQuery);
        pst6.setInt(1, userId);
        int rowsDeleted = pst6.executeUpdate();
        pst6.close();
        
        if (rowsDeleted > 0) {
            JOptionPane.showMessageDialog(this,
                "✓ Your account has been permanently deleted.\n\n" +
                "All your data has been removed from NOVA Learning Center.\n\n" +
                "Thank you for using our platform.\n" +
                "We hope to see you again someday!",
                "Account Deleted",
                JOptionPane.INFORMATION_MESSAGE);
            
            // Clear session
            AccountManager.clearSession();
            
            // Close all windows
            for (java.awt.Window window : java.awt.Window.getWindows()) {
                window.dispose();
            }
            
            // Open login
            new LOGIN().setVisible(true);
        }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,
            "Database error occurred:\n\n" + e.getMessage() + "\n\n" +
            "Account deletion failed. Please try again or contact support.",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SECURITY().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}