/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.realeastprojectasin;

import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.util.*;
import java.util.List;
import java.sql.*;
import java.util.*;
import java.util.List;
import java.awt.Color;
/**
 *
 * @author gelo
 */
public class TAKEQUIZ extends javax.swing.JFrame {
    private Connection connection;
    private int quizId;
    private String quizName;
    
    private List<Question> questions;
    private int currentIndex = 0;
    private int correctCount = 0;
    private int totalQuestions = 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TAKEQUIZ.class.getName());

    /**
     * Creates new form TAKEQUIZ
     */
        public TAKEQUIZ() {
        initComponents();
    }
        
    public TAKEQUIZ(int quizId, String quizName) {
            this.quizId = quizId;
            this.quizName = quizName;
        initComponents();
            setSize(600, 300); // or setSize(800, 700)
    setLocationRelativeTo(null);
            // Initialize
    connection = DBConnection.getConnection();
    questions = new ArrayList<>();
    
    // Set title
    jLabel1.setText("Taking Quiz: " + quizName);
    
    // Hide buttons initially
    jButton2.setVisible(false); // Next Question
    jButton3.setVisible(false); // Finish Quiz
    jLabel4.setVisible(false); // Feedback label
    
    // Load questions
    loadQuestions();
    
    if (questions.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No questions in this quiz!");
        dispose();
        return;
    }
    
    totalQuestions = questions.size();
    displayQuestion(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 750));

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton2");

        jRadioButton3.setText("jRadioButton3");

        jRadioButton4.setText("jRadioButton4");

        jLabel4.setText("jLabel4");

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Finish");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jButton1)
                                .addGap(140, 140, 140)
                                .addComponent(jButton2)
                                .addGap(149, 149, 149)
                                .addComponent(jButton3))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(35, 35, 35)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Question q = questions.get(currentIndex);
    
    // Get selected answer
    String selectedAnswer = null;
    if (jRadioButton1.isSelected()) selectedAnswer = "A";
    else if (jRadioButton2.isSelected()) selectedAnswer = "B";
    else if (jRadioButton3.isSelected()) selectedAnswer = "C";
    else if (jRadioButton4.isSelected()) selectedAnswer = "D";
    
    if (selectedAnswer == null) {
        JOptionPane.showMessageDialog(this, "Please select an answer!");
        return;
    }
    
    // Check if correct
    boolean isCorrect = selectedAnswer.equals(q.correctAnswer);
    
    if (isCorrect) {
        correctCount++;
        jLabel4.setText("✅ Correct!");
        jLabel4.setForeground(new Color(46, 204, 113)); // Green
    } else {
        jLabel4.setText("❌ Wrong! The correct answer is: " + q.correctAnswer + ")");
        jLabel4.setForeground(new Color(231, 76, 60)); // Red
    }
    
    // Show feedback
    jLabel4.setVisible(true);
    
    // Disable radios (can't change answer)
    jRadioButton1.setEnabled(false);
    jRadioButton2.setEnabled(false);
    jRadioButton3.setEnabled(false);
    jRadioButton4.setEnabled(false);
    
    // Hide Check Answer button
    jButton1.setVisible(false);
    
    // Show appropriate next button
    if (currentIndex < totalQuestions - 1) {
        jButton2.setVisible(true); // Next Question
    } else {
        jButton3.setVisible(true); // Finish Quiz
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      displayQuestion(currentIndex + 1);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       finishQuiz();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TAKEQUIZ().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
 private void loadQuestions() {
    try {
        String query = "SELECT * FROM questions WHERE quiz_id = ? ORDER BY question_id";
        PreparedStatement ps = connection.prepareStatement(query);
        ps.setInt(1, quizId);
        ResultSet rs = ps.executeQuery();
        
        while (rs.next()) {
            Question q = new Question();
            q.questionId = rs.getInt("question_id");
            q.questionText = rs.getString("question_text");
            q.optionA = rs.getString("option_a");
            q.optionB = rs.getString("option_b");
            q.optionC = rs.getString("option_c");
            q.optionD = rs.getString("option_d");
            q.correctAnswer = rs.getString("correct_answer");
            questions.add(q);
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

private void displayQuestion(int index) {
    currentIndex = index;
    Question q = questions.get(index);
    
    // Update header
    jLabel2.setText("Question " + (index + 1) + " of " + totalQuestions);
    jProgressBar1.setMaximum(totalQuestions);
    jProgressBar1.setValue(index + 1);
    jProgressBar1.setString((index + 1) + "/" + totalQuestions);
    
    // Update question and options
    jLabel3.setText("<html><body style='width:700px'><b>" + (index + 1) + ". " + q.questionText + "</b></body></html>");
    jRadioButton1.setText("<html>A) " + q.optionA + "</html>");
    jRadioButton2.setText("<html>B) " + q.optionB + "</html>");
    jRadioButton3.setText("<html>C) " + q.optionC + "</html>");
    jRadioButton4.setText("<html>D) " + q.optionD + "</html>");
    
    
    // Reset button states
    jButton1.setVisible(true); // Check Answer
    jButton1.setEnabled(false); // Disabled until answer selected
    jButton2.setVisible(false); // Next Question
    jButton3.setVisible(false); // Finish Quiz
    jLabel4.setVisible(false); // Feedback
    
    // Enable radios
    jRadioButton1.setEnabled(true);
    jRadioButton2.setEnabled(true);
    jRadioButton3.setEnabled(true);
    jRadioButton4.setEnabled(true);
    
    // Add listeners to enable Check Answer button when option selected
    addRadioListeners();
}

private void addRadioListeners() {
    java.awt.event.ActionListener listener = e -> jButton1.setEnabled(true);
    
    jRadioButton1.addActionListener(listener);
    jRadioButton2.addActionListener(listener);
    jRadioButton3.addActionListener(listener);
    jRadioButton4.addActionListener(listener);
}
private void finishQuiz() {
    double score = (correctCount * 100.0) / totalQuestions;
    
    // Save to database
    try {
        connection.setAutoCommit(false);
        
        // Insert response
        String insertResp = "INSERT INTO responses (quiz_id, user_id, score, completed_at) VALUES (?, ?, ?, NOW())";
        PreparedStatement ps = connection.prepareStatement(insertResp, Statement.RETURN_GENERATED_KEYS);
        ps.setInt(1, quizId);
        ps.setInt(2, AccountManager.getCurrentUserId());
        ps.setDouble(3, score);
        ps.executeUpdate();
        
        // Create notification
        String insertNotif = "INSERT INTO notifications (user_id, message, type, created_at, is_read) VALUES (?, ?, ?, NOW(), false)";
        PreparedStatement ps2 = connection.prepareStatement(insertNotif);
        ps2.setInt(1, AccountManager.getCurrentUserId());
        ps2.setString(2, String.format("You scored %.0f%% on '%s'", score, quizName));
        ps2.setString(3, "quiz_taken");
        ps2.executeUpdate();
        
        connection.commit();
        connection.setAutoCommit(true);
        
        // Show final results
        String message;
        if (score >= 90) {
            message = "Excellent!";
        } else if (score >= 75) {
            message = "Great job!";
        } else if (score >= 50) {
            message = "Good effort!";
        } else {
            message = "Keep practicing!";
        }
        
        JOptionPane.showMessageDialog(this,
            String.format("Quiz Complete!\n\nYour Score: %.2f%%\n\nCorrect: %d / %d\n\n%s", 
                score, correctCount, totalQuestions, message),
            "Results",
            JOptionPane.INFORMATION_MESSAGE);
        
        // Close and go back
        dispose();
        new VIEWQUIZ().setVisible(true);
        
    } catch (SQLException e) {
        try { connection.rollback(); } catch (SQLException ex) {}
        JOptionPane.showMessageDialog(this, "Error saving results: " + e.getMessage());
        e.printStackTrace();
    }
}

// ============================================
// HELPER CLASS
// ============================================
class Question {
    int questionId;
    String questionText;
    String optionA, optionB, optionC, optionD;
    String correctAnswer;
}
}

