/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.realeastprojectasin;

import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.text.SimpleDateFormat;
/**
 *
 * @author gelo
 */
public class VIEWQUIZ extends javax.swing.JFrame {
        private Connection connection;
    private JPanel quizzesContainer;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VIEWQUIZ.class.getName());

    /**
     * Creates new form VIEWQUIZ
     */
    public VIEWQUIZ() {
        initComponents();
         connection = DBConnection.getConnection();
        
        // Setup container panel for quiz cards
        quizzesContainer = new JPanel();
        quizzesContainer.setLayout(new BoxLayout(quizzesContainer, BoxLayout.Y_AXIS));
        quizzesContainer.setBackground(new Color(30, 40, 60)); // Dark blue like your design
        
        // Put container inside your scrollpane
        jScrollPane1.setViewportView(quizzesContainer);
        
        // Load quizzes from database
        loadQuizzes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setText("Quizzes");

        jPanel1.setBackground(new java.awt.Color(10, 38, 71));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel2.setText("Back");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(352, 352, 352))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

   this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VIEWQUIZ().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
private void loadQuizzes() {
    // Clear existing
    quizzesContainer.removeAll();
    
    try {
        // Query to get all quizzes with creator info, question count, AND creator_id
        String query = 
            "SELECT q.quiz_id, q.quiz_name, q.course, u.username as creator, " +
            "q.created_at, q.creator_id, COUNT(qs.question_id) as question_count " +
            "FROM quizzes q " +
            "JOIN users u ON q.creator_id = u.user_id " +
            "LEFT JOIN questions qs ON q.quiz_id = qs.quiz_id " +
            "GROUP BY q.quiz_id " +
            "ORDER BY q.created_at DESC";
        
        Statement stmt = connection.createStatement();
        ResultSet rs = stmt.executeQuery(query);
        
        boolean hasQuizzes = false;
        while (rs.next()) {
            hasQuizzes = true;
            
            int quizId = rs.getInt("quiz_id");
            String quizName = rs.getString("quiz_name");
            String course = rs.getString("course");
            String creator = rs.getString("creator");
            String createdAt = rs.getString("created_at");
            int questionCount = rs.getInt("question_count");
            int creatorId = rs.getInt("creator_id"); // ✅ GET CREATOR ID
            
            // Create quiz card WITH creator_id
            JPanel quizCard = createQuizCard(quizId, quizName, course, creator, createdAt, questionCount, creatorId);
            
            // Add to container
            quizzesContainer.add(quizCard);
            quizzesContainer.add(Box.createVerticalStrut(15)); // Spacing between cards
        }
        
        if (!hasQuizzes) {
            JLabel noQuizLabel = new JLabel("No quizzes available yet");
            noQuizLabel.setFont(new Font("Segoe UI", Font.ITALIC, 16));
            noQuizLabel.setForeground(Color.LIGHT_GRAY);
            noQuizLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
            quizzesContainer.add(noQuizLabel);
        }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,
            "Error loading quizzes: " + e.getMessage(),
            "Database Error",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    
    // Refresh display
    quizzesContainer.revalidate();
    quizzesContainer.repaint();
}
private JPanel createQuizCard(int quizId, String quizName, String course, 
                              String creator, String date, int questionCount, int creatorId) {
    // Main card panel
    JPanel card = new JPanel();
    card.setLayout(new BorderLayout(15, 10));
    card.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(new Color(100, 150, 200), 2),
        BorderFactory.createEmptyBorder(15, 20, 15, 20)
    ));
    card.setMaximumSize(new Dimension(700, 150));
    card.setPreferredSize(new Dimension(700, 150));
    card.setBackground(new Color(45, 55, 75));
    
    // Left side - Quiz info
    JPanel infoPanel = new JPanel();
    infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.Y_AXIS));
    infoPanel.setOpaque(false);
    
    JLabel nameLabel = new JLabel(quizName);
    nameLabel.setFont(new Font("Segoe UI", Font.BOLD, 18));
    nameLabel.setForeground(Color.WHITE);
    nameLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
    
    JLabel courseLabel = new JLabel("Course: " + course);
    courseLabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));
    courseLabel.setForeground(new Color(200, 200, 200));
    courseLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
    
    JLabel creatorLabel = new JLabel("By: " + creator + " • " + date);
    creatorLabel.setFont(new Font("Segoe UI", Font.ITALIC, 12));
    creatorLabel.setForeground(new Color(150, 150, 150));
    creatorLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
    
    JLabel questionLabel = new JLabel(questionCount + " questions");
    questionLabel.setFont(new Font("Segoe UI", Font.PLAIN, 12));
    questionLabel.setForeground(new Color(100, 200, 255));
    questionLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
    
    infoPanel.add(nameLabel);
    infoPanel.add(Box.createVerticalStrut(5));
    infoPanel.add(courseLabel);
    infoPanel.add(Box.createVerticalStrut(3));
    infoPanel.add(creatorLabel);
    infoPanel.add(Box.createVerticalStrut(3));
    infoPanel.add(questionLabel);
    
    // ✅ CHECK IF CURRENT USER IS OWNER
    int currentUserId = AccountManager.getCurrentUserId();
    boolean isOwner = (creatorId == currentUserId);
    
    // Right side - Buttons panel
    JPanel buttonsPanel = new JPanel();
    buttonsPanel.setLayout(new BoxLayout(buttonsPanel, BoxLayout.Y_AXIS));
    buttonsPanel.setOpaque(false);
    
    // Take Quiz Button (always visible)
    JButton takeQuizBtn = new JButton("Take Quiz");
    takeQuizBtn.setFont(new Font("Segoe UI", Font.BOLD, 14));
    takeQuizBtn.setBackground(new Color(46, 204, 113));
    takeQuizBtn.setForeground(Color.WHITE);
    takeQuizBtn.setFocusPainted(false);
    takeQuizBtn.setPreferredSize(new Dimension(120, 40));
    takeQuizBtn.setMaximumSize(new Dimension(120, 40));
    takeQuizBtn.setAlignmentX(Component.CENTER_ALIGNMENT);
    takeQuizBtn.addActionListener(e -> openTakeQuiz(quizId, quizName));
    
    buttonsPanel.add(takeQuizBtn);
    
    // ✅ IF OWNER, ADD EDIT AND DELETE BUTTONS
    if (isOwner) {
        buttonsPanel.add(Box.createVerticalStrut(8));
        
        // Edit button
        JButton editBtn = new JButton("Edit");
        editBtn.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        editBtn.setBackground(new Color(59, 130, 246));
        editBtn.setForeground(Color.WHITE);
        editBtn.setFocusPainted(false);
        editBtn.setPreferredSize(new Dimension(120, 30));
        editBtn.setMaximumSize(new Dimension(120, 30));
        editBtn.setAlignmentX(Component.CENTER_ALIGNMENT);
        editBtn.addActionListener(e -> editQuiz(quizId, quizName));
        
        buttonsPanel.add(editBtn);
        buttonsPanel.add(Box.createVerticalStrut(5));
        
        // Delete button
        JButton deleteBtn = new JButton("Delete");
        deleteBtn.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        deleteBtn.setBackground(new Color(239, 68, 68));
        deleteBtn.setForeground(Color.WHITE);
        deleteBtn.setFocusPainted(false);
        deleteBtn.setPreferredSize(new Dimension(120, 30));
        deleteBtn.setMaximumSize(new Dimension(120, 30));
        deleteBtn.setAlignmentX(Component.CENTER_ALIGNMENT);
        deleteBtn.addActionListener(e -> deleteQuiz(quizId, quizName));
        
        buttonsPanel.add(deleteBtn);
        
        // Owner badge
        JLabel ownerLabel = new JLabel("Your Quiz");
        ownerLabel.setFont(new Font("Segoe UI", Font.BOLD, 10));
        ownerLabel.setForeground(new Color(251, 191, 36));
        ownerLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        buttonsPanel.add(Box.createVerticalStrut(5));
        buttonsPanel.add(ownerLabel);
    }
    
    card.add(infoPanel, BorderLayout.CENTER);
    card.add(buttonsPanel, BorderLayout.EAST);
    
    return card;
}
// Open quiz for taking
private void openTakeQuiz(int quizId, String quizName) {
    // Check if user already took this quiz (optional warning)
    try {
        String query = "SELECT COUNT(*) as count FROM responses WHERE quiz_id = ? AND user_id = ?";
        PreparedStatement ps = connection.prepareStatement(query);
        ps.setInt(1, quizId);
        ps.setInt(2, AccountManager.getCurrentUserId());
        ResultSet rs = ps.executeQuery();
        
        if (rs.next() && rs.getInt("count") > 0) {
            int choice = JOptionPane.showConfirmDialog(this,
                "You've already taken this quiz before.\n\nTake it again?",
                "Retake Quiz",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            
            if (choice != JOptionPane.YES_OPTION) return;
        }
        
    } catch (SQLException e) {
        e.printStackTrace();
    }
    
    // Open TAKEQUIZ frame
    new TAKEQUIZ(quizId, quizName).setVisible(true);
    this.dispose();
}

// Edit quiz
private void editQuiz(int quizId, String quizName) {
    int confirm = JOptionPane.showConfirmDialog(this,
        "Edit quiz: " + quizName + "?",
        "Edit Quiz",
        JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(this,
            "Edit feature coming soon!\n\n" +
            "You'll be able to modify quiz questions and details.",
            "Feature In Progress",
            JOptionPane.INFORMATION_MESSAGE);
        
        // When EDITQUIZ is ready:
        // new EDITQUIZ(quizId).setVisible(true);
        // this.dispose();
    }
}

// Delete quiz
private void deleteQuiz(int quizId, String quizName) {
    // First confirmation
    int confirm = JOptionPane.showConfirmDialog(this,
        "⚠️ Delete Quiz: " + quizName + " ⚠️\n\n" +
        "This will permanently delete:\n" +
        "• All questions in this quiz\n" +
        "• All student responses\n" +
        "• All related data\n\n" +
        "This action CANNOT be undone!\n\n" +
        "Are you absolutely sure?",
        "Confirm Deletion",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE);
    
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }
    
    // Second confirmation - type quiz name
    String verification = JOptionPane.showInputDialog(this,
        "Type the quiz name to confirm deletion:\n\n\"" + quizName + "\"",
        "Final Confirmation",
        JOptionPane.WARNING_MESSAGE);
    
    if (verification == null || !verification.equals(quizName)) {
        JOptionPane.showMessageDialog(this,
            "Quiz name doesn't match. Deletion cancelled.",
            "Cancelled",
            JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    try {
        int currentUserId = AccountManager.getCurrentUserId();
        
        // Verify ownership
        String checkQuery = "SELECT creator_id FROM quizzes WHERE quiz_id = ?";
        PreparedStatement checkPst = connection.prepareStatement(checkQuery);
        checkPst.setInt(1, quizId);
        ResultSet rs = checkPst.executeQuery();
        
        if (rs.next()) {
            int creatorId = rs.getInt("creator_id");
            
            if (creatorId != currentUserId) {
                JOptionPane.showMessageDialog(this,
                    "Permission denied! You can only delete your own quizzes.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        rs.close();
        checkPst.close();
        
        // Delete quiz (CASCADE will handle related records)
        String deleteQuery = "DELETE FROM quizzes WHERE quiz_id = ?";
        PreparedStatement deletePst = connection.prepareStatement(deleteQuery);
        deletePst.setInt(1, quizId);
        
        int rowsDeleted = deletePst.executeUpdate();
        deletePst.close();
        
        if (rowsDeleted > 0) {
            // Add notification
            String notifQuery = "INSERT INTO notifications (user_id, message, type, created_at) " +
                               "VALUES (?, ?, ?, NOW())";
            PreparedStatement notifPst = connection.prepareStatement(notifQuery);
            notifPst.setInt(1, currentUserId);
            notifPst.setString(2, "You deleted quiz: " + quizName);
            notifPst.setString(3, "quiz_deleted");
            notifPst.executeUpdate();
            notifPst.close();
            
            JOptionPane.showMessageDialog(this,
                "✓ Quiz \"" + quizName + "\" deleted successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
            
            // Refresh quiz list
            loadQuizzes(); // Just call loadQuizzes again
        }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,
            "Error deleting quiz:\n\n" + e.getMessage(),
            "Database Error",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}

// Refresh quiz list after deletion
private void refreshQuizList() {
    // Clear existing quiz cards
    jPanel1.removeAll(); // Replace 'quizContainer' with your actual container name
    
    // Reload quizzes
    loadQuizzes(); // Call your existing method to load quizzes
    
    // Refresh UI
    jPanel1.revalidate();
    jPanel1.repaint();
}

}
